name: capsule_apps
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  animated_custom_dropdown: ^3.1.1
  cloud_firestore: ^6.0.1
  firebase_core: ^4.1.0
  flex_color_scheme: ^8.3.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_flavorizr: ^2.4.1  
  get: ^4.7.2
  get_storage: ^2.1.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
